spring:
  datasource:
    url: jdbc:h2:mem:librarydb
    schema: classpath:schema.sql
    initialization-mode: always
    show-sql: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: "library"

    show-sql: false
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

library:
  kafka-topic-name:
    get-out-msg: book-msg-get-out
    get-out-book: book-get-out