DROP TABLE IF EXISTS BOOK_COMMENT;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USERSROLE;

CREATE TABLE AUTHOR (ID BIGINT IDENTITY PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRE (ID BIGINT IDENTITY PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOK (ID BIGINT IDENTITY PRIMARY KEY, TITLE VARCHAR(255), AUTHORID BIGINT, GENREID BIGINT);
CREATE TABLE BOOK_COMMENT (ID BIGINT IDENTITY PRIMARY KEY, BOOKID BIGINT, COMMENT VARCHAR(1000));
CREATE TABLE USERS (ID BIGINT IDENTITY PRIMARY KEY, LOGIN VARCHAR(255), PASSWORD VARCHAR(255));
CREATE TABLE USERSROLE (ID BIGINT IDENTITY PRIMARY KEY, USERID BIGINT, ROLE VARCHAR(255));

ALTER TABLE AUTHOR ADD CONSTRAINT K01_AUTHOR UNIQUE (NAME);
ALTER TABLE GENRE ADD CONSTRAINT K01_GENRE UNIQUE (NAME);
ALTER TABLE BOOK ADD CONSTRAINT K01_BOOK  UNIQUE (TITLE, AUTHORID);

ALTER TABLE BOOK ADD CONSTRAINT K02_BOOK FOREIGN KEY (AUTHORID) REFERENCES AUTHOR;
ALTER TABLE BOOK ADD CONSTRAINT K03_BOOK FOREIGN KEY (GENREID) REFERENCES GENRE;
ALTER TABLE BOOK_COMMENT ADD CONSTRAINT K01_BOOK_COMMENT FOREIGN KEY (BOOKID) REFERENCES BOOK;