DROP TABLE IF EXISTS Currency;
DROP TABLE IF EXISTS CurrencyRate;

CREATE TABLE Currency (ID BIGINT IDENTITY PRIMARY KEY, Name VARCHAR(3));
CREATE TABLE CurrencyRate (ID BIGINT IDENTITY PRIMARY KEY, CurrencyBuyID BIGINT, CurrencySellID BIGINT, RateValue NUMERIC(32,14), RateDate DATE);
