DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE AUTHOR (ID BIGINT IDENTITY PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRE (ID BIGINT IDENTITY PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOK (ID BIGINT IDENTITY PRIMARY KEY, TITLE VARCHAR(255), AUTHORID BIGINT, GENREID BIGINT);

ALTER TABLE AUTHOR ADD CONSTRAINT K01_AUTHOR UNIQUE (NAME);
ALTER TABLE GENRE ADD CONSTRAINT K01_GENRE UNIQUE (NAME);
ALTER TABLE BOOK ADD CONSTRAINT K01_BOOK  UNIQUE (TITLE, AUTHORID);

ALTER TABLE BOOK ADD CONSTRAINT KO2_BOOK FOREIGN KEY (AUTHORID) REFERENCES AUTHOR;
ALTER TABLE BOOK ADD CONSTRAINT KO3_BOOK FOREIGN KEY (GENREID) REFERENCES GENRE;