insert into currency (name)
select 'DZD' union all
select 'ARS' union all
select 'AUD' union all
select 'BSD' union all
select 'BHD' union all
select 'BDT' union all
select 'AMD' union all
select 'BBD' union all
select 'BMD' union all
select 'BTN' union all
select 'BOB' union all
select 'BWP' union all
select 'BZD' union all
select 'SBD' union all
select 'BND' union all
select 'MMK' union all
select 'BIF' union all
select 'KHR' union all
select 'CAD' union all
select 'CVE' union all
select 'KYD' union all
select 'LKR' union all
select 'CLP' union all
select 'CNY' union all
select 'COP' union all
select 'KMF' union all
select 'CRC' union all
select 'HRK' union all
select 'CUP' union all
select 'CZK' union all
select 'DKK' union all
select 'DOP' union all
select 'SVC' union all
select 'ETB' union all
select 'ERN' union all
select 'FKP' union all
select 'FJD' union all
select 'DJF' union all
select 'GMD' union all
select 'GIP' union all
select 'GTQ' union all
select 'GNF' union all
select 'GYD' union all
select 'HTG' union all
select 'HNL' union all
select 'HKD' union all
select 'HUF' union all
select 'ISK' union all
select 'INR' union all
select 'IDR' union all
select 'IRR' union all
select 'IQD' union all
select 'ILS' union all
select 'JMD' union all
select 'JPY' union all
select 'KZT' union all
select 'JOD' union all
select 'KES' union all
select 'KPW' union all
select 'KRW' union all
select 'KWD' union all
select 'KGS' union all
select 'LAK' union all
select 'LBP' union all
select 'LSL' union all
select 'LRD' union all
select 'LYD' union all
select 'MOP' union all
select 'MWK' union all
select 'MYR' union all
select 'MVR' union all
select 'MUR' union all
select 'MXN' union all
select 'MNT' union all
select 'MDL' union all
select 'MAD' union all
select 'OMR' union all
select 'NAD' union all
select 'NPR' union all
select 'ANG' union all
select 'AWG' union all
select 'VUV' union all
select 'NZD' union all
select 'NIO' union all
select 'NGN' union all
select 'NOK' union all
select 'PKR' union all
select 'PAB' union all
select 'PGK' union all
select 'PYG' union all
select 'PEN' union all
select 'PHP' union all
select 'QAR' union all
select 'RUB' union all
select 'RWF' union all
select 'SHP' union all
select 'SAR' union all
select 'SCR' union all
select 'SLL' union all
select 'SGD' union all
select 'VND' union all
select 'SOS' union all
select 'ZAR' union all
select 'SSP' union all
select 'SZL' union all
select 'SEK' union all
select 'CHF' union all
select 'SYP' union all
select 'THB' union all
select 'TOP' union all
select 'TTD' union all
select 'AED' union all
select 'TND' union all
select 'UGX' union all
select 'MKD' union all
select 'EGP' union all
select 'GBP' union all
select 'TZS' union all
select 'USD' union all
select 'UYU' union all
select 'UZS' union all
select 'WST' union all
select 'YER' union all
select 'TWD' union all
select 'VES' union all
select 'MRU' union all
select 'STN' union all
select 'CUC' union all
select 'ZWL' union all
select 'BYN' union all
select 'TMT' union all
select 'GHS' union all
select 'SDG' union all
select 'UYI' union all
select 'RSD' union all
select 'MZN' union all
select 'AZN' union all
select 'RON' union all
select 'TRY' union all
select 'XAF' union all
select 'XCD' union all
select 'XOF' union all
select 'XPF' union all
select 'XDR' union all
select 'ZMW' union all
select 'SRD' union all
select 'MGA' union all
select 'COU' union all
select 'AFN' union all
select 'TJS' union all
select 'AOA' union all
select 'BGN' union all
select 'CDF' union all
select 'BAM' union all
select 'EUR' union all
select 'UAH' union all
select 'GEL' union all
select 'PLN' union all
select 'BRL';


